colcon/colcon-ros

colcon_ros/task/ros.py
connects to colcon/colcon-cmake#6
The help text now says
```
Arguments for 'ros' packages:
--ament-cmake-args [* [* ...]]
Arbitrary arguments which are passed to all
'ament_cmake' packages. Args that start with "-" must
be prefixed with a space. If using bash then use
--ament-cmake-args \ -Dvar=val
If using Windows cmd then use
--ament-cmake-args " -Dvar=val"
--catkin-cmake-args [* [* ...]]
Arbitrary arguments which are passed to all 'catkin'
packages. Args that start with "-" must be prefixed
with a space. If using bash then use
--catkin-cmake-args \ -Dvar=val
If using Windows cmd then use
--catkin-cmake-args " -Dvar=val"
```
=> Document to quote spaces on windows

colcon_ros/package_identification/ros.py
This is necessary for ROS 1 devel jobs since some repos (e.g. [moveit](https://github.com/ros-planning/moveit/)) still contain dry packages.
The easiest to reproduce and see the effect of the patch is to invoke `colcon list` on such a repo.
=> ignore dry ROS packages

colcon_ros/task/ros.py
Addresses some test failures in ROS 1 packages reported in ros-infrastructure/ros_buildfarm_config#117.
Follow up of #9.
=> set ROS_PACKAGE_PATH for catkin packages

colcon_ros/package_identification/ros.py
If an "unsupported" build type is found the package identification will still report the type as "ros.something" and it would fail later in the process when no extension with that e.g. build task is being found.
Follow up of #31.
=> remove build type check

colcon_ros/package_identification/ros.py, test/spell_check.words
Currently the Python packages must have a `setup.py` file which is handled by `colcon-python-setup-py`. This patch adds support for Python package which specify their meta information in the `setup.cfg` file (like this package does).
=> support ROS Python packages using a setup.cfg file

setup.cfg
With the latest releases of `flake8` and its plugins this pinning is not necessary anymore. It was originally added in #6.
=> remove pycodestyle pinned version

colcon_ros/task/catkin/__init__.py, colcon_ros/task/catkin/build.py, colcon_ros/task/catkin/test.py, test/spell_check.words
The patch consists of three parts:
* refactor the `PYTHONPATH` hook generation to be reused across both verbs
* by default build the `tests` target of catkin packages (in addition to the default target) and add the option `--catkin-skip-building-tests` to skip it
* enabled by colcon/colcon-cmake#31
* generate a proper environment for `build/devel` when running the tests
* enabled by colcon/colcon-core#161
=> improve testing of ROS 1 packages

colcon_ros/task/__init__.py, colcon_ros/task/ament_cmake/build.py, colcon_ros/task/cmake/build.py
Instead of simply concatenating them ROS 2 prefix paths are always inserted *before* ROS 1 prefix paths.
That ensures that ROS 2 packages can be `find_package()`-ed where as ROS 1 packages are discovered using `pkg-config`.
=> ensure ROS 2 prefix paths are before ROS 1 prefix paths

setup.cfg
This patch addresses the failing CI due to the recent release of `pytest` 5.0.
Similar to colcon/colcon-core#200.
=> suppress deprecation warnings from third party code

colcon_ros/package_identification/ros.py
Since the parsed file might not even be a ROS package manifest I didn't pick a higher log level.
=> log a debug message if the package.xml file can't be parsed successfully

colcon_ros/task/ament_python/build.py, test/spell_check.words
The first commit reverts #74 - to again implicitly install marker and manifest files. Based on the 
Discourse conversation https://discourse.ros.org/t/can-we-chat-about-breaking-changes-in-stable-releases/10689 as well as several other reports.
The second commit changes the logic to only install the files implicitly if the package doesn't already do it explicitly using the `data_files` option. In the case the files are implicitly installed by `colcon-ros` a warning is printed to notify the user that this "magic" will be removed in the future.
=> readd implicitly installing marker and manifest files but warn about it

colcon_ros/package_identification/ros.py, debian/patches/setup.cfg.patch, setup.cfg, stdeb.cfg
I would suggest this should be at least a warning. Being only debug, will make it hard for beginners to find the correct log message in the log file. It took me a long time to figure out why my package wouldn't compile.
=> increase severity of log message for package parse errors from debug to warn

colcon_ros/package_identification/ros.py, debian/patches/setup.cfg.patch, setup.cfg, stdeb.cfg
Fixes #65. Depends on colcon/colcon-core#251. Needs a version dependency bump as soon as the dependency has been released.
=> check that no arguments are passed to the setup() function in setup.py

colcon_ros/task/ament_python/build.py
Follow up of https://github.com/colcon/colcon-ros/pull/79#issuecomment-532951865.
Several packages will need update to not show this warning for them.
=> warn about missing explicit marker installation

colcon_ros/task/catkin/__init__.py, colcon_ros/task/catkin/build.py, colcon_ros/task/catkin/test.py, test/spell_check.words
Replacing the Python 2 specific hard coded path with an approach which reads the `PYTHON_INSTALL_DIR` from the CMake cache and works for Python 2 as well as 3.
This makes it work to build ROS 1 Noetic which uses Python 3.
=> update PYTHONPATH for catkin packages with Python 3

colcon_ros/package_identification/ros.py, setup.cfg, stdeb.cfg
Alternative to #86 using colcon/colcon-python-setup-py#30. Needs a version dependency bump as soon as the dependency has been released.
=> use improved Python package identification

colcon_ros/task/ament_python/build.py
The implementation of setup_py_data includes a key for 'data_files' with
a value of None if the attribute is not specified.
As a result, `setup_py_data.get('data_files', [])` can return `None` if
no data_files are specified.
When data_files is none it actually triggers a failure in colcon-core's
get_data_files_mapping function:
Traceback (most recent call last):
File
"/home/jenkins-agent/workspace/ci_linux/venv/lib/python3.6/site-packages/colcon_core/executor/__init__.py", line 91, in __call__
rc = await self.task(*args, **kwargs)
File
"/home/jenkins-agent/workspace/ci_linux/venv/lib/python3.6/site-packages/colcon_core/task/__init__.py", line 92, in __call__
return await task_method(*args, **kwargs)
File
"/home/jenkins-agent/workspace/ci_linux/venv/lib/python3.6/site-packages/colcon_ros/ta …
=> Ensure data_files is not None.

colcon_ros/task/ament_cmake/build.py, colcon_ros/task/catkin/build.py
Partially addresses colcon/colcon-cmake#70.
Since ament/cmake CMake args are not different than the standard CMake the example with `--help` doesn't make much sense.
Instead colcon/colcon-cmake#72 provides the additional context.
=> reduce help message for --ament/catkin-cmake-args

colcon_ros/task/cmake/build.py
Since they are being generated a few lines below: https://github.com/colcon/colcon-ros/blob/b35bc8550b11578646c74e90c933fdd899cc5162/colcon_ros/task/cmake/build.py#L39-L40
=> skip redundant environment script generation

colcon_ros/task/catkin/build.py
This PR adds `colcon build --symlink-install` support for `catkin`.
Currently, `--symlink-install` is not handled for catkin, so it doesn't work.
I added `-DCATKIN_SYMLINK_INSTALL=ON` if `--symlink-install` is specified.
https://github.com/colcon/colcon-ros/commit/c0729650ea0400805d6ef98e34761dc7ee2d76d6#diff-e7857422a7528e2f883dd0de18b0e30dR61-R62
This is almost the same way as `ament-cmake`.
https://github.com/colcon/colcon-ros/blob/master/colcon_ros/task/ament_cmake/build.py#L60-L63
```sh-session
###################################
###################################
$ docker run --rm -it osrf/ros:melodic-desktop-full
##################################################
##################################################
total 24
lrwxrwxrwx 1 root root 76 Jun 29 15:01 README -> …
```
=> Support catkin symlink-install

colcon_ros/task/ament_cmake/build.py, colcon_ros/task/catkin/build.py, colcon_ros/task/cmake/build.py
Alternatively, we could throw a known, possibly custom, type from colcon_cmake
and catch it here.
For now, suppressing the linter error seems much easier.
=> Suppress blind except flake8 error

colcon_ros/package_augmentation/ros_ament_python.py, colcon_ros/package_identification/ros.py, setup.cfg
This will give other extensions and users finer control over ROS package identification, and aligns this extension better with the same process as is performed in [colcon-core]( https://github.com/colcon/colcon-core/blob/c4c622f4e961aaa9fb40c91eed5d02054992da8b/colcon_core/package_augmentation/python.py#L60
) and [colcon-python-setup-py](https://github.com/colcon/colcon-python-setup-py/blob/496290a52b4e979b26d4f6390020b4db8de4f197/colcon_python_setup_py/package_augmentation/python_setup_py.py#L53).
The only change in behavior during typical use should be that ROS packages which declare their `build_type` as `ament_python` but which contain no `setup.py` files will no longer be skipped with an error message. Instead, the package will fail to build with a message stating that the `setup.py` …
=> Move ament_python metadata extraction to augmentation module

colcon_ros/package_identification/ros.py
This information could be useful to other extensions.
=> Add package maintainer information to metadata

colcon_ros/package_identification/ros.py, test/test_dependency_metadata.py
While I don't think we should discriminate between dependency types for general use, this is useful metadata in some contexts and is easy to include.
Follows colcon/colcon-core#564
=> Add 'origin' metadata to ROS dependencies

colcon_ros/package_identification/ros.py
In other colcon packages, the augmentation phase is responsible for adding this information. Two reasons this is a good idea:
1. This information isn't part of a package 'identity'
2. This allows a user to specify the package type in a colcon.pkg file and still get the dependency information parsed correctly.
For example, here's the augmentation logic for `python` packages for reading dependencies: https://github.com/colcon/colcon-core/blob/7b70e61175ab735ea5448ab6e88b4882975566b5/colcon_core/package_augmentation/python.py#L53-L55
=> Move dependency and version processing to augmentation

stdeb.cfg
The OSRF-provided `python3-catkin-pkg-modules` is still preferred, but we should allow use of the upstream package as well. Either will work fine with `colcon-ros`.
The motivation behind this change is to allow the Package Cloud repository to be usable without the contents of the ROS bootstrap repository, which is where `python3-catkin-pkg-modules` comes from.
=> Support upstream catkin_pkg deb

colcon_ros/package_identification/ros.py, test/spell_check.words
See ros-infrastructure/catkin_pkg#369
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=20943)](http://ci.ros2.org/job/ci_linux/20943/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=15234)](http://ci.ros2.org/job/ci_linux-aarch64/15234/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=21617)](http://ci.ros2.org/job/ci_windows/21617/)
=> Add logic for excluding group workaround dependencies

colcon_ros/package_identification/ros.py, test/test_package_identification_ros.py
- Expose public functions for performing package augmentation
- Ensure dependency categories are set on descriptors even when those categories are empty (to align with colcon_core)
=> Improve reusability in colcon_ros.package_identification.ros
