colcon/colcon-ros

- colcon_ros/package_identification/ignore.py
- colcon_ros/package_identification/ros.py
Connect to colcon/colcon-core#44.
> rename SkipLocationException to IgnoreLocationException

- colcon_ros/task/ros.py
Follow up of colcon/colcon-core#63.
> update help text for greedy options

- colcon_ros/task/ros.py
Requires colcon/colcon-core#75.
> set AMENT|CATKIN_TEST_RESULTS_DIR based on test result base

- colcon_ros/task/ros.py
This enabled to build ROS 2 packages on top of e.g. the Debian packages which don't set the `CMAKE_PREFIX_PATH` (they only set up the runtime environment using `AMENT_PREFIX_PATH` but not a build environment).
> extend the CMAKE_PREFIX_PATH with the AMENT_PREFIX_PATH

- setup.cfg
> add dependency on colcon-pkg-config

- colcon_ros/task/ros.py
Apply #21 to plain CMake packages too.
Based on https://answers.ros.org/question/296462/compilation-error-building-against-binary-bouncy-could-not-find-fastrtps/
> extend CMAKE_PREFIX_PATH with AMENT_PREFIX_PATH for plain CMake pkgs

- colcon_ros/task/ros.py
Fixes colcon/colcon-zsh#12. Replaces #27. Requires colcon/colcon-core#88.
> create additional hooks based on available shell extensions

- colcon_ros/task/catkin/build.py
> Add custom catkin environment hooks

- colcon_ros/package_identification/ros.py
- setup.cfg
Similar to colcon/colcon-core#109.
> update log.warn (deprecated) to log.warning

- .travis.yml
- colcon_ros/package_identification/ros.py
- debian/patches/setup.cfg.patch
- setup.cfg
- stdeb.cfg
- test/test_dependency_metadata.py
For #39 
Depends on  colcon/colcon-core#106
> Add version metadata to dependencies in PackageDescriptor

- test/test_dependency_metadata.py
- test/test_flake8.py
Same as colcon/colcon-core#127.
> Fix flake8 test logic

- colcon_ros/prefix_path/ament.py
- test/spell_check.words
> fix sourcing isolated underlays for ament packages

- colcon_ros/prefix_path/catkin.py
Similar as #60 just for `catkin` packages. Fixes #61.
> fix sourcing isolated underlays for catkin packages

- colcon_ros/package_identification/ros.py
> add version to package metadata

- colcon_ros/task/catkin/build.py
Fixes environment variables like `ROS_ETC_DIR` and `ROS_ROOT` when built in isolation.
> set CATKIN_ENV_HOOK_WORKSPACE for env hooks provided by catkin packages

- colcon_ros/task/ament_python/build.py
> fix check for installed package manifest on Windows

- colcon_ros/task/catkin/build.py
- debian/patches/setup.cfg.patch
- setup.cfg
- stdeb.cfg
> use an empty value which for .dsv files has always been the prefix path

- colcon_ros/task/catkin/build.py
- test/spell_check.words
Just for shorter, more readable code.
> use contextlib.suppress

- colcon_ros/task/ament_cmake/build.py
- colcon_ros/task/catkin/build.py
- colcon_ros/task/cmake/build.py
> only add ROS env hooks when package has an install target

- colcon_ros/task/ament_cmake/build.py
- colcon_ros/task/catkin/build.py
- colcon_ros/task/cmake/build.py
> fix error handling when build failed and targets can't be retrieved

- colcon_ros/package_augmentation/ros_ament_index.py
- setup.cfg
- test/spell_check.words
- test/test_ament_index_augmentation.py
For use when inspecting installed packages.
> Add extension for getting dependencies from ament_index

- debian/patches/setup.cfg.patch
> Update debian patch to align with recent changes

- colcon_ros/argcomplete_completer/catkin_cmake_args.py
- colcon_ros/package_identification/ros.py
- colcon_ros/prefix_path/ament.py
- colcon_ros/prefix_path/catkin.py
- colcon_ros/task/__init__.py
- colcon_ros/task/ament_cmake/build.py
- colcon_ros/task/ament_cmake/test.py
- colcon_ros/task/ament_python/build.py
- colcon_ros/task/ament_python/test.py
- colcon_ros/task/catkin/__init__.py
- colcon_ros/task/catkin/build.py
- colcon_ros/task/catkin/test.py
- colcon_ros/task/cmake/build.py
- colcon_ros/task/cmake/test.py
- debian/patches/setup.cfg.patch
- setup.cfg
- stdeb.cfg
Follow-up to colcon/colcon-core#480.
> Require Python 3.6, use f-strings
